# Generated by Django 4.0 on 2021-12-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=255)),
                ('pret', models.FloatField()),
                ('categorie', models.CharField(max_length=255)),
                ('descriere', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
