# Generated by Django 3.2.9 on 2021-12-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produse',
            new_name='Produs',
        ),
    ]
