# Generated by Django 3.2.9 on 2021-12-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
